### ISSUE TITLE
Повторяющиеся коды ИБ при многосайтовости

### ISSUE THREAD

**Issue by nook-ru** [maximaster/tools.orm#10]
Имхо сабж вполне допустим, и не вызывает проблем при работе штатных компонентов самого модуля инфоблоков.

Даже если вызывать `\Maximaster\Tools\Orm\Iblock\ElementTable::compileEntity()` с `ID` инфоблока, свойства с привязкой к другим ИБ будут компилироваться по символьному коду этого ИБ.

Сейчас это приводит к исключению: *Существует 2 инфоблока(ов) с CODE = xxx*.

Кажется, вполне безопасно будет заменить здесь код на ID инфоблоков: https://github.com/maximaster/tools.orm/blob/master/src/Maximaster/Tools/Orm/Iblock/ElementTable.php#L63-L64

**Comment by mmjurov** [comment]
На первый взгляд не вижу тут ничего криминального. Волью в master после разрешения вопроса с локализацией
