### ISSUE TITLE
Библиотека не найдена

### ISSUE THREAD

**Issue by maxlyaptsev** [maximaster/tools.orm#8]
The requested package maximaster/tools.orm could not be found in any version, there may be a typo in the package name.
http://joxi.ru/EA4dLvpCbKVBAb

php composer.phar search maximaster
maximaster/tools.twig Модуль подключения шаблонизатора twig к битриксу
maximaster/tools.events Библиотека осуществляет помощь для автоматической загрузки обработчиков событий при соблюдении определенной структуры
maximaster/twig.filewatcher File watcher для преобразования Twig-шаблонов в HTML

**Comment by mmjurov** [comment]
В чем собственно вопрос?
Данная библиотека намеренно не опубликована на packagist. Она еще слишком нестабильна. 
Чтобы подключить ее к себе, нужно прописать путь до репозитория в секции `repositories` в своем composer.json
